import type { Metadata } from "next";
import {
  Inria_Serif,
  Inter,
  Inria_Sans,
  Cairo,
  Aref_Ruqaa,
  Rubik,
  Markazi_Text,
} from "next/font/google";
import "./globals.css";
import Header from "./Header";
export const inriaSerif = Aref_Ruqaa({
  subsets: ["latin"],
  weight: ["400", "700"],
});

const inriaSans = Markazi_Text({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ar" dir="rtl">
      <body
        className={
          inriaSans.className + " w-full max-w-[1200px] mx-auto  relative "
        }
      >
        <Header />
        {children}
      </body>
    </html>
  );
}
